[package]
name = "base"
version = "0.1.0"
authors = ["Automata Team"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
chrono = "0.4.38"
tokio = { version = "1.0", features = ["time", "macros", "rt-multi-thread", "sync"] }